name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC
  workflow_dispatch: # for manual workflow trigger

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>
          # meta
          # API_BASE_URL: https://wakapi.dev/api
          # content
